version: "3.9"

services:
  web_crawler:
    image: web_crawler:latest
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    container_name: web_crawler
    hostname: web_crawler
    restart: unless-stopped
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    command: sh -c "cargo watch -x run"
    networks:
      web_crawler:
        ipv4_address: 172.11.6.2

networks:
  web_crawler:
    ipam:
      config:
        - subnet: 172.11.0.0/16
          ip_range: 172.11.6.0/24
          gateway: 172.11.6.1
